{{- if .Values.haproxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
        log stdout format raw local0 info
        maxconn 4096

    defaults
        log             global
        mode            http
        option          httplog
        timeout connect 5s
        timeout client  50s
        timeout server  50s
        timeout tunnel  3600s

    resolvers myresolver
        parse-resolv-conf
        hold valid 10s

    peers mypeers
        {{- $name := include "jitsi-scaler.haproxy.fullname" . }}
        {{- range $i := until (int .Values.haproxy.replicaCount) }}
        peer {{ $name }}-{{ $i }} {{ $name }}-{{ $i }}.{{ $name }}-peers:1024
        {{- end }}

    frontend jitsi-frontend
        bind *:{{ .Values.haproxy.service.port }}
        option forwardfor
        option http-keep-alive

        stick-table type string len 64 size 100k expire 30m peers mypeers

        # Shard0 routing for auxiliary services before sticking
        acl is_aux_service path_beg /etherpad /excalidraw
        use_backend shard0_backend if is_aux_service

        stick store-request url_param(room)

        default_backend jitsi_shard_pool

    backend jitsi_shard_pool
        balance roundrobin
        option httpchk
        http-check send meth GET hdr User-Agent haproxy
        http-reuse safe

        stick match url_param(room) table jitsi-frontend

        {{- range $key, $value := .Values }}
        {{-   if and (regexMatch "^shard[0-9]+$" $key) $value.enabled }}
        server {{ $key }} {{ $.Release.Name }}-{{ $key }}-web:80 check resolvers myresolver init-addr none
        {{-   end }}
        {{- end }}

    # Dedicated backend for Shard0 auxiliary services
    backend shard0_backend
        server shard0 {{ .Release.Name }}-shard0-web:80 check

  {{- range $key, $value := .Values.haproxy.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
