{{- if .Values.haproxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
        log stdout format raw local0 info
        maxconn 10000

    defaults
        log             global
        mode            http
        option          httplog
        option          dontlognull
        timeout connect 5s
        timeout client  50s
        timeout server  50s
        timeout tunnel  3600s

    peers mypeers
        # podManagementPolicy is set as Parallel for haproxy statefulsets to
        # make their services available at the initial stage. Peers expects all
        # services to be available to allow HAProxy to start.
        {{- $name := include "jitsi-scaler.haproxy.fullname" . }}
        {{- $port := .Values.haproxy.servicePeers.port }}
        {{- range $i := until (int .Values.haproxy.replicaCount) }}
        peer {{ $name }}-{{ $i }} {{ $name }}-{{ $i }}.{{ $name }}-peers:{{ $port }}
        {{- end }}

    frontend jitsi-frontend
        bind *:{{ .Values.haproxy.service.port }}
        option forwardfor
        option http-keep-alive

        default_backend jitsi_backend

    backend jitsi_backend
        balance roundrobin
        option httpchk
        http-check expect status 200-399,405
        http-reuse safe

        # jitsi and excalidraw use room as querystring in their websockets.
        # etherpad uses padId as querystring in its websockets.
        # room in path is not important since it is only exist for static files.
        acl has_room url_param(room) -m found
        acl has_pad  url_param(padId) -m found

        stick-table type string len 128 size 100k expire 24h peers mypeers
        stick on url_param(room) if has_room
        stick on url_param(padId) if !has_room has_pad

        {{- range $key, $value := .Values }}
        {{-   if and (regexMatch "^shard[0-9]+$" $key) $value.enabled }}
        server {{ $key }} {{ $.Release.Name }}-{{ $key }}-web:{{ $.Values.haproxy.backend.port }} check
        {{-   end }}
        {{- end }}

  {{- range $key, $value := .Values.haproxy.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
