{{- if .Values.haproxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
        log stdout format raw local0 info
        maxconn 10000

    defaults
        log             global
        mode            http
        option          httplog
        option          dontlognull
        timeout connect 5s
        timeout client  50s
        timeout server  50s
        timeout tunnel  3600s

    resolvers myresolver
        parse-resolv-conf
        hold valid 10s

    peers mypeers
        {{- $name := include "jitsi-scaler.haproxy.fullname" . }}
        {{- $port := .Values.haproxy.servicePeers.port }}
        {{- range $i := until (int .Values.haproxy.replicaCount) }}
        peer {{ $name }}-{{ $i }} {{ $name }}-{{ $i }}.{{ $name }}-peers:{{ $port }}
        {{- end }}

    frontend jitsi-frontend
        bind *:{{ .Values.haproxy.service.port }}
        option forwardfor
        option http-keep-alive

        # Shard0 routing for auxiliary services before sticking
        acl is_aux_service path_beg /etherpad /excalidraw
        use_backend aux_backend if is_aux_service

        default_backend jitsi_backend

    backend jitsi_backend
        balance roundrobin
        option httpchk
        http-check expect status 200-399,405
        http-reuse safe

        stick-table type string len 128 size 100k expire 2h peers mypeers
        stick on url_param(room) if { url_param(room) -m found }

        {{- range $key, $value := .Values }}
        {{-   if and (regexMatch "^shard[0-9]+$" $key) $value.enabled }}
        server {{ $key }} {{ $.Release.Name }}-{{ $key }}-web:80 check
        {{-   end }}
        {{- end }}

    backend aux_backend
        server shard0 {{ .Release.Name }}-shard0-web:80 check

  {{- range $key, $value := .Values.haproxy.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
