apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
    {{- with .Values.haproxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.haproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.haproxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitsi-scaler.haproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-scaler.haproxy.selectorLabels" . | nindent 8 }}
        {{- with (mergeOverwrite (dict) .Values.global.podLabels .Values.haproxy.podLabels) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/haproxy/configmap.yaml") . | sha256sum | quote }}
        {{- with (mergeOverwrite (dict) .Values.global.podAnnotations .Values.haproxy.podAnnotations) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.haproxy.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.haproxy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}"
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
              name: {{ include "jitsi-meet.haproxy.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.haproxy.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: {{ include "jitsi-scaler.haproxy.fullname" . }}
