{{- if and
       .Values.haproxy.ingress.enabled
       (not .Values.haproxy.gateway.enabled)
-}}
{{-   $svcPort := .Values.haproxy.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
  {{- with .Values.haproxy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.haproxy.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.haproxy.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.haproxy.ingress.host | quote }}
      secretName: {{ .Values.haproxy.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.haproxy.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.haproxy.ingress.paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "jitsi-scaler.haproxy.fullname" . }}
                port:
                  {{- if kindIs "float64" $svcPort }}
                  number: {{ $svcPort }}
                  {{- else }}
                  name: {{ $svcPort }}
                  {{- end }}
          {{- end }}
{{- end }}
