{{- if .Values.haproxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}-peers
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: peers
      port: 1024
      protocol: TCP
      targetPort: peers
  selector:
    {{- include "jitsi-scaler.haproxy.selectorLabels" . | nindent 4 }}
{{- end }}
