{{- if .Values.haproxy.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jitsi-scaler.haproxy.fullname" . }}
  labels:
    {{- include "jitsi-scaler.haproxy.labels" . | nindent 4 }}
    {{- with .Values.haproxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.haproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.haproxy.replicaCount }}
  serviceName: {{ include "jitsi-scaler.haproxy.fullname" . }}-peers
  selector:
    matchLabels:
      {{- include "jitsi-scaler.haproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-scaler.haproxy.selectorLabels" . | nindent 8 }}
        {{- with (mergeOverwrite (dict) .Values.global.podLabels .Values.haproxy.podLabels) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/haproxy/configmap.yaml") . | sha256sum | quote }}
        {{- with (mergeOverwrite (dict) .Values.global.podAnnotations .Values.haproxy.podAnnotations) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.haproxy.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.haproxy.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "jitsi-scaler.haproxy.fullname" . }}
        {{- with .Values.haproxy.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}"
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
              name: {{ include "jitsi-scaler.haproxy.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.haproxy.service.port }}
              protocol: TCP
            - name: peers
              containerPort: 1024
              protocol: TCP
          {{- with .Values.haproxy.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.haproxy.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            {{- with .Values.haproxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      {{- with .Values.haproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
